<script lang="ts">
  import { onMount, afterUpdate } from "svelte";
  import {
    ethers,
    formatUnits,
    parseUnits,
    type BrowserProvider,
    type BigNumberish
  } from "ethers";
  import tacoLogo from "../../public/taco-tezos-blue.jpg";
  import config from "../config";

  export let userAddress: undefined | string, provider: BrowserProvider;

  let userBalance: undefined | BigNumberish = undefined;
  let contract: ethers.Contract;
  let transferAmount: string | null = null;
  let transferTo: string | null = null;

  const claim = async () => {
    try {
      const tx = await contract.claim();
      const receipt = await tx.wait();
      console.log(receipt);
      // receipt.status = 0 -> error
      // receipt.status = 1 -> confirmed
    } catch (error) {
      console.error(error);
    }
  };

  const transfer = async () => {
    try {
      if (!transferAmount) throw "No amount";
      if (!transferTo) throw "No recipient";

      const amountToTransfer = parseUnits(transferAmount, config.decimals);
      const tx = await contract.transfer(transferTo, amountToTransfer);
      const receipt = await tx.wait();
      console.log(receipt);
    } catch (error) {
      console.error(error);
    }
  };

  onMount(async () => {
    // creates the instance of the contract
    if (!contract) {
      const signer = await provider.getSigner();
      contract = new ethers.Contract(
        config.contractAddress,
        config.contractAbi,
        signer
      );
    }
  });

  afterUpdate(async () => {
    // if the user is connected, checks their balance
    if (userAddress) {
      const contract = new ethers.Contract(
        config.contractAddress,
        config.contractAbi,
        provider
      );
      const balance = await contract.balanceOf(userAddress);
      if (balance) {
        userBalance = balance;
      } else {
        userBalance = undefined;
      }
    }
  });
</script>

<style lang="scss">
  .body {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 50px;

    .roll-in-left {
      -webkit-animation: roll-in-left 0.6s ease-out 0.5s both;
      animation: roll-in-left 0.6s ease-out 0.5s both;

      img {
        width: 100px;
        height: 100px;
        border-radius: 50%;
        border: solid 8px #003ee0;
      }
    }

    .description {
      text-align: center;
      width: 50%;
    }

    .user-balance {
      border-radius: 5px;
      background-color: #9f329f;
      color: white;
      font-size: 1.1rem;
      padding: 10px;
    }

    .transfer-input {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 10px;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2023-6-8 16:16:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation roll-in-left
 * ----------------------------------------
 */
  @-webkit-keyframes roll-in-left {
    0% {
      -webkit-transform: translateX(-800px) rotate(-540deg);
      transform: translateX(-800px) rotate(-540deg);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0) rotate(0deg);
      transform: translateX(0) rotate(0deg);
      opacity: 1;
    }
  }
  @keyframes roll-in-left {
    0% {
      -webkit-transform: translateX(-800px) rotate(-540deg);
      transform: translateX(-800px) rotate(-540deg);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0) rotate(0deg);
      transform: translateX(0) rotate(0deg);
      opacity: 1;
    }
  }
</style>

<div class="body">
  <div class="roll-in-left">
    <img src={tacoLogo} alt="taco-logo" />
  </div>
  <div class="description">
    <p>Welcome to the TACO EVM Token!</p>
    <p>
      This is a the first token to be built in an EVM rollup deployed on the
      Tezos blockchain.
    </p>
    <p>
      The TACO Token is a standard ERC-20 token, now made better by managing it
      in a Tezos smart rollup.
    </p>
    {#if userBalance}
      <p class="user-balance">
        Your current balance is {formatUnits(userBalance, config.decimals)}
      </p>
      <div class="transfer-input">
        <input
          type="text"
          placeholder="Transfer TAC to"
          class="address"
          bind:value={transferTo}
        />
        <input
          type="text"
          placeholder="Amount of TAC"
          bind:value={transferAmount}
        />
        <button class="blue" on:click={transfer}>Send</button>
      </div>
    {:else}
      <p>Click the button below to claim your free tokens!</p>
      <button class="claim" on:click={claim}>Claim 1,000 TAC</button>
    {/if}
  </div>
</div>
