<script lang="ts">
  import { onMount, afterUpdate } from "svelte";
  import {
    ethers,
    formatUnits,
    parseUnits,
    type BrowserProvider,
    type BigNumberish
  } from "ethers";
  import tacoLogo from "/taco-tezos-blue.jpg";
  import config from "../config";
  import Modal from "./Modal.svelte";

  export let userAddress: undefined | string,
    provider: BrowserProvider,
    hasClaimed: boolean;

  let userBalance: undefined | BigNumberish = undefined;
  let contract: ethers.Contract;
  let transferAmount: string | null = null;
  let transferTo: string | null = null;
  let isTransferring = false;
  let isClaiming = false;
  let showModal = false;
  let modalText = "No text";

  const handleModal = (text: string) => {
    showModal = true;
    modalText = text;
    setTimeout(() => {
      showModal = false;
    }, 3_000);
  };

  const claim = async () => {
    isClaiming = true;
    try {
      const tx = await contract.claim();
      handleModal("Claiming your tokens...");
      const receipt = await tx.wait();
      console.log(receipt);
      // receipt.status = 0 -> error
      // receipt.status = 1 -> confirmed
      if (receipt.status === 1) {
        handleModal("Tokens claimed!");
        // updates the balance
        userBalance =
          BigInt(userBalance ? userBalance : 0) +
          BigInt(1000000000000000000000);
      } else {
        handleModal("An error has occurred");
      }
    } catch (error) {
      console.error(error);
      handleModal("An error has occurred");
    } finally {
      isClaiming = true;
    }
  };

  const transfer = async () => {
    isTransferring = true;
    try {
      if (!transferAmount) throw "No amount";
      if (!transferTo) throw "No recipient";

      const amountToTransfer = parseUnits(transferAmount, config.decimals);
      const tx = await contract.transfer(transferTo, amountToTransfer);
      handleModal("Processing transfer...");
      const receipt = await tx.wait();
      if (receipt.status === 1) {
        handleModal("Transfer confirmed!");
        transferAmount = null;
        transferTo = null;
        userBalance = BigInt(userBalance) - amountToTransfer;
      } else {
        handleModal("An error has occurred");
      }
    } catch (error) {
      console.error(error);
      handleModal("An error has occurred");
    } finally {
      isTransferring = false;
    }
  };

  onMount(async () => {
    // creates the instance of the contract
    if (!contract) {
      const signer = await provider.getSigner();
      contract = new ethers.Contract(
        config.contractAddress,
        config.contractAbi,
        signer
      );
    }
  });

  afterUpdate(async () => {
    // if the user is connected, checks their balance
    if (userAddress) {
      const contract = new ethers.Contract(
        config.contractAddress,
        config.contractAbi,
        provider
      );
      const balance = await contract.balanceOf(userAddress);
      if (balance) {
        userBalance = balance;
      } else {
        userBalance = undefined;
      }
    }
  });
</script>

<style lang="scss">
  .body {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 50px;

    .roll-in-left {
      -webkit-animation: roll-in-left 0.6s ease-out 0.5s both;
      animation: roll-in-left 0.6s ease-out 0.5s both;

      img {
        width: 100px;
        height: 100px;
        border-radius: 50%;
        border: solid 8px #003ee0;
      }
    }

    .description {
      text-align: center;
      width: 50%;
    }

    .user-balance {
      border-radius: 5px;
      background-color: #9f329f;
      color: white;
      font-size: 1.1rem;
      padding: 10px;
    }

    .transfer-input {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 10px;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2023-6-8 16:16:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation roll-in-left
 * ----------------------------------------
 */
  @-webkit-keyframes roll-in-left {
    0% {
      -webkit-transform: translateX(-800px) rotate(-540deg);
      transform: translateX(-800px) rotate(-540deg);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0) rotate(0deg);
      transform: translateX(0) rotate(0deg);
      opacity: 1;
    }
  }
  @keyframes roll-in-left {
    0% {
      -webkit-transform: translateX(-800px) rotate(-540deg);
      transform: translateX(-800px) rotate(-540deg);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0) rotate(0deg);
      transform: translateX(0) rotate(0deg);
      opacity: 1;
    }
  }
</style>

<div class="body">
  <div class="roll-in-left">
    <img src={tacoLogo} alt="taco-logo" />
  </div>
  <div class="description">
    <p>Welcome to the TACO EVM Token!</p>
    <p>
      This is a the first token to be built in an EVM rollup deployed on the
      Tezos blockchain.
    </p>
    <p>
      The TACO Token is a standard ERC-20 token, now made better by managing it
      in a Tezos smart rollup.
    </p>
    {#if userBalance && userAddress}
      <p class="user-balance">
        Your current balance is {formatUnits(userBalance, config.decimals)}
      </p>
      <div class="transfer-input">
        <input
          type="text"
          placeholder="Transfer TACO to"
          class="address"
          bind:value={transferTo}
          disabled={isTransferring}
        />
        <input
          type="text"
          placeholder="Amount of TACO"
          bind:value={transferAmount}
          disabled={isTransferring}
        />
        <button class="blue" disabled={isTransferring} on:click={transfer}>
          {#if isTransferring}
            Sending...
          {:else}
            Send
          {/if}
        </button>
      </div>
    {/if}
    {#if userAddress && !hasClaimed}
      <div>
        {#if isClaiming}
          <p>Please wait</p>
          <button class="claim">Claiming 1,000 TAC...</button>
        {:else}
          <p>Click the button below to claim your free tokens!</p>
          <button class="claim" on:click={claim}>Claim 1,000 TAC</button>
        {/if}
      </div>
    {:else if !userAddress}
      <p>Please connect your wallet to continue</p>
    {/if}
  </div>
</div>
<Modal show={showModal} text={modalText} />
