<script lang="ts">
  import tacoLogo from "../../public/taco-tezos-blue.jpg";
  import abi from "../assets/abi.json";
</script>

<style lang="scss">
  .body {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 50px;

    .roll-in-left {
      -webkit-animation: roll-in-left 0.6s ease-out 0.5s both;
      animation: roll-in-left 0.6s ease-out 0.5s both;

      img {
        width: 100px;
        height: 100px;
        border-radius: 50%;
        border: solid 8px #003ee0;
      }
    }

    .description {
      text-align: center;
      width: 50%;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2023-6-8 16:16:31
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation roll-in-left
 * ----------------------------------------
 */
  @-webkit-keyframes roll-in-left {
    0% {
      -webkit-transform: translateX(-800px) rotate(-540deg);
      transform: translateX(-800px) rotate(-540deg);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0) rotate(0deg);
      transform: translateX(0) rotate(0deg);
      opacity: 1;
    }
  }
  @keyframes roll-in-left {
    0% {
      -webkit-transform: translateX(-800px) rotate(-540deg);
      transform: translateX(-800px) rotate(-540deg);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0) rotate(0deg);
      transform: translateX(0) rotate(0deg);
      opacity: 1;
    }
  }
</style>

<div class="body">
  <div class="roll-in-left">
    <img src={tacoLogo} alt="taco-logo" />
  </div>
  <div class="description">
    <p>Welcome to the Tacos EVM Token!</p>
    <p>
      This is a the first token to be built in an EVM rollup deployed on the
      Tezos blockchain.
    </p>
    <p>
      The Tacos Token is a standard ERC-20 token, now made better by managing it
      in a Tezos smart rollup.
    </p>
    <p>Click the button below to claim your free tokens!</p>
    <button class="claim">Claim 1,000 TAC</button>
  </div>
</div>
